/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EscrowV2Interface extends Interface {
    getFunction(nameOrSignature: "approveMilestone" | "approvedCount" | "client" | "completedCount" | "ethPerMilestone" | "freelancer" | "isComplete" | "markCompleted" | "milestones" | "remainingBalance" | "totalMilestones"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "JobCompleted" | "JobCreated" | "MilestoneApproved" | "MilestoneCompleted"): EventFragment;

    encodeFunctionData(functionFragment: 'approveMilestone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approvedCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'client', values?: undefined): string;
encodeFunctionData(functionFragment: 'completedCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'ethPerMilestone', values?: undefined): string;
encodeFunctionData(functionFragment: 'freelancer', values?: undefined): string;
encodeFunctionData(functionFragment: 'isComplete', values?: undefined): string;
encodeFunctionData(functionFragment: 'markCompleted', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'milestones', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'remainingBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalMilestones', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'approveMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approvedCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'client', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completedCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ethPerMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freelancer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isComplete', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markCompleted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'milestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'remainingBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalMilestones', data: BytesLike): Result;
  }

  
    export namespace JobCompletedEvent {
      export type InputTuple = [totalPaid: BigNumberish];
      export type OutputTuple = [totalPaid: bigint];
      export interface OutputObject {totalPaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobCreatedEvent {
      export type InputTuple = [client: AddressLike, freelancer: AddressLike, totalMilestones: BigNumberish, ethPerMilestone: BigNumberish, totalFunded: BigNumberish];
      export type OutputTuple = [client: string, freelancer: string, totalMilestones: bigint, ethPerMilestone: bigint, totalFunded: bigint];
      export interface OutputObject {client: string, freelancer: string, totalMilestones: bigint, ethPerMilestone: bigint, totalFunded: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [milestoneId: BigNumberish, payout: BigNumberish];
      export type OutputTuple = [milestoneId: bigint, payout: bigint];
      export interface OutputObject {milestoneId: bigint, payout: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneCompletedEvent {
      export type InputTuple = [milestoneId: BigNumberish];
      export type OutputTuple = [milestoneId: bigint];
      export interface OutputObject {milestoneId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EscrowV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): EscrowV2;
    waitForDeployment(): Promise<this>;

    interface: EscrowV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveMilestone: TypedContractMethod<
      [milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approvedCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    client: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    completedCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ethPerMilestone: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    freelancer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isComplete: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    markCompleted: TypedContractMethod<
      [milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    milestones: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    remainingBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalMilestones: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveMilestone'): TypedContractMethod<
      [milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approvedCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'client'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'completedCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ethPerMilestone'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'freelancer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isComplete'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'markCompleted'): TypedContractMethod<
      [milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'milestones'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'remainingBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalMilestones'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'JobCompleted'): TypedContractEvent<JobCompletedEvent.InputTuple, JobCompletedEvent.OutputTuple, JobCompletedEvent.OutputObject>;
getEvent(key: 'JobCreated'): TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'MilestoneCompleted'): TypedContractEvent<MilestoneCompletedEvent.InputTuple, MilestoneCompletedEvent.OutputTuple, MilestoneCompletedEvent.OutputObject>;

    filters: {
      
      'JobCompleted(uint256)': TypedContractEvent<JobCompletedEvent.InputTuple, JobCompletedEvent.OutputTuple, JobCompletedEvent.OutputObject>;
      JobCompleted: TypedContractEvent<JobCompletedEvent.InputTuple, JobCompletedEvent.OutputTuple, JobCompletedEvent.OutputObject>;
    

      'JobCreated(address,address,uint256,uint256,uint256)': TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
      JobCreated: TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
    

      'MilestoneApproved(uint256,uint256)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'MilestoneCompleted(uint256)': TypedContractEvent<MilestoneCompletedEvent.InputTuple, MilestoneCompletedEvent.OutputTuple, MilestoneCompletedEvent.OutputObject>;
      MilestoneCompleted: TypedContractEvent<MilestoneCompletedEvent.InputTuple, MilestoneCompletedEvent.OutputTuple, MilestoneCompletedEvent.OutputObject>;
    
    };
  }