/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EscrowInterface extends Interface {
    getFunction(nameOrSignature: "contractAddress" | "createOrder" | "deposit" | "orders" | "refundFundsToBuyer" | "releaseFundsToSeller" | "sendDelivery" | "transactionCount"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'contractAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'createOrder', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'orders', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'refundFundsToBuyer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'releaseFundsToSeller', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'sendDelivery', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transactionCount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'contractAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundFundsToBuyer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFundsToSeller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sendDelivery', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transactionCount', data: BytesLike): Result;
  }

  

  export interface Escrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): Escrow;
    waitForDeployment(): Promise<this>;

    interface: EscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    contractAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createOrder: TypedContractMethod<
      [_buyer: AddressLike, _seller: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    orders: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint] & {id: bigint, buyer: string, seller: string, amount: bigint, status: bigint }],
      'view'
    >
    

    
    refundFundsToBuyer: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    releaseFundsToSeller: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    sendDelivery: TypedContractMethod<
      [_transactionCount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transactionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'contractAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createOrder'): TypedContractMethod<
      [_buyer: AddressLike, _seller: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'orders'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint] & {id: bigint, buyer: string, seller: string, amount: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'refundFundsToBuyer'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseFundsToSeller'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sendDelivery'): TypedContractMethod<
      [_transactionCount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transactionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }